# TODO: Pick a better name than easy
[package]
name = "easy"
version = "0.1.0"
edition = "2021"
authors = ["Caleb Schoepp <hey@calebschoepp.com"]

[lib]
name = "easy"
path = "src/lib.rs"

[[bin]]
name = "cli"
path = "src/main.rs"

[dependencies]
structopt = "0.3.26"
